#!/usr/bin/env bash

# Shared paper configuration. Source this file after setting MODEL to one of:
# ours, ours_ray, or ours_rayma.
MODEL="${MODEL:-ours_rayma}"

export POINT3R_MEMORY_UPDATE_MODE=ordered_kway
export POINT3R_MEMORY_IMPL=tensor
export POINT3R_ORDERED_UPDATE_IMPL=tensor
export POINT3R_KWAY_NUM_SLOTS=8
export POINT3R_KWAY_NUM_SLOTS_FORCE=8
export POINT3R_ORDERED_THETA_BINS=16
export POINT3R_ORDERED_PHI_BINS=8
export POINT3R_ORDERED_RHO_BINS=32
export POINT3R_ORDERED_WAY_POLICY=appearance
export POINT3R_ENCODE_CHUNK_SIZE=100
export POINT3R_CONFSELECT_MERGE_THRESHOLD=0.90
export POINT3R_CONFSELECT_STATS=0
export POINT3R_CGMC=1
export POINT3R_CGMC_DROP_QUANTILE="${POINT3R_CGMC_DROP_QUANTILE:-0.25}"
export POINT3R_CGMC_MIN_CONF=0.0
export POINT3R_CGMC_WEIGHTED_MERGE=1
export POINT3R_SPARSE_READOUT=1
export POINT3R_SPARSE_MODE=max
export POINT3R_SPARSE_MAX_TOKENS=640
export POINT3R_SPARSE_GLOBAL_ANCHORS=128
export POINT3R_SPARSE_NEIGHBOR_RANGE=1

case "$MODEL" in
  ours)
    module=dust3r.point3r_kway_frame_sparse_q35_confselect
    export POINT3R_RAYAWARE_UPDATE=0
    export POINT3R_LC_ENABLED=0
    ;;
  ours_ray)
    module=dust3r.point3r_kway_frame_sparse_q35_confselect_rayaware_v82e_balanced_predecoder_pose
    export POINT3R_RAY_DUAL_BANK=1
    export POINT3R_RAY_BANK_UPDATE_EVERY=4
    export POINT3R_RAYAWARE_UPDATE=1
    export POINT3R_RAY_PAPER_UPDATE=1
    export POINT3R_RAY_KWAY_DIVERSE_UPDATE=0
    export POINT3R_RAY_HYBRID_READOUT=1
    export POINT3R_RAY_POSE_INPUT_ONLY=1
    export POINT3R_RAY_POSE_POST_DECODER_ONLY=0
    export POINT3R_RAY_POSE_ONLY_ENSEMBLE=0
    export POINT3R_RAY_POSE_INPUT_TOKENS=128
    export POINT3R_RAY_POSE_INPUT_MAX_WEIGHT=0.025
    export POINT3R_RAY_POSE_INPUT_TEMPERATURE=0.10
    ;;
  ours_rayma)
    module=dust3r.point3r_kway_frame_sparse_q35_confselect_rayaware_v106_fresh_bank_pose
    export POINT3R_RAY_DUAL_BANK=1
    export POINT3R_RAY_BANK_UPDATE_EVERY=1
    export POINT3R_V106_RAY_BANK_UPDATE_EVERY=1
    export POINT3R_RAYAWARE_UPDATE=1
    export POINT3R_RAY_PAPER_UPDATE=1
    export POINT3R_RAY_KWAY_DIVERSE_UPDATE=0
    export POINT3R_RAY_HYBRID_READOUT=1
    export POINT3R_RAY_POSE_INPUT_ONLY=1
    export POINT3R_RAY_POSE_POST_DECODER_ONLY=0
    export POINT3R_RAY_POSE_ONLY_ENSEMBLE=0
    export POINT3R_RAY_POSE_INPUT_TOKENS=128
    export POINT3R_V106_POSE_INPUT_WEIGHT=0.15
    export POINT3R_RAY_POSE_INPUT_TEMPERATURE=0.10
    ;;
  *)
    echo "MODEL must be ours, ours_ray, or ours_rayma" >&2
    return 2 2>/dev/null || exit 2
    ;;
esac

export POINT3R_POSE_MODEL_MODULE="$module"
export POINT3R_DEPTH_MODEL_MODULE="$module"

# Verified state-regularization chain used by Ours-Ray/Ours-RayMA pose runs.
if [[ "$MODEL" != "ours" ]]; then
  export POINT3R_LC_ENABLED=1
  export POINT3R_LC_LOOP_DETECTION=0
  export POINT3R_LC_ODOM_MAX_LAG=3
  export POINT3R_LC_FULL_SE3=0
  export POINT3R_LC_DECOUPLED_SE3=0
  export POINT3R_LC_ROTATION_GRAPH=1
  export POINT3R_LC_DIRECT_RAY_ODOM=0
  export POINT3R_LC_STATE_REGULARIZATION=1
  export POINT3R_LC_STATE_LIE_INCREMENT=1
  export POINT3R_LC_STATE_TRANS_STRENGTH=30
  export POINT3R_LC_STATE_ROT_STRENGTH=30
  export POINT3R_LC_STATE_LOCAL_ROT_MODE=0
  export POINT3R_LC_STATE_LOW_RAY_FUSION=1
  export POINT3R_LC_STATE_RAY_FUSION_TRANSPORT_ONLY=1
  export POINT3R_LC_STATE_CYCLE_OBSERVABLE_FUSION=0
  export POINT3R_LC_STATE_RAY_FUSION_PRIOR=1
  export POINT3R_LC_STATE_RAY_FUSION_DELTA_DEG=2
  export POINT3R_LC_STATE_RAY_FUSION_MAX_STEP_DEG=2
  export POINT3R_LC_ODOM_CENTERED_ROTATION=0
  export POINT3R_LC_ODOM_ESSENTIAL_ROTATION=0
  export POINT3R_RAY_POINTER_LOOP_GRAPH=0
  export POINT3R_RAY_POINTER_LOOP_PGO=0
fi
